### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Mad-Qj** [wecooperate/iDefender#32]
Have you dropped localization support? Because the localization file(.qm) does not work and there is no menu for language selection.

**Comment by wecooperate** [comment]
The current translation is not very professional, we license it to our partners, and will launch an independent international product in the future.
It's coming soon.



---Original---
From: ***@***.***&gt;
Date: Wed, May 22, 2024 14:47 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [wecooperate/iDefender] Localization (Issue #32)




 
Have you dropped localization support? Because the localization file(.qm) does not work and there is no menu for language selection.

**Comment by wecooperate** [comment]
please refer to  https://idefender.trustsing.com/
