### ISSUE TITLE
希望可以监控拦截剪贴板事件

### ISSUE THREAD

**Issue by QPYIDRWIMG** [wecooperate/iDefender#37]
希望可以监控拦截剪贴板事件。比如：读取、写入剪贴板

**Comment by wecooperate** [comment]
读取剪切板是支持的，需要开启增强模式。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月28日(周六) 下午4:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] 希望可以监控拦截剪贴板事件 (Issue #37)




 
希望可以监控拦截剪贴板事件。比如：读取、写入剪贴板

**Comment by QPYIDRWIMG** [comment]
> 读取剪切板是支持的，需要开启增强模式。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月28日(周六) 下午4:11 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [wecooperate/iDefender] 希望可以监控拦截剪贴板事件 (Issue #37) 希望可以监控拦截剪贴板事件。比如：读取、写入剪贴板 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谢谢。请问监控读取剪贴板事件该怎么做？我创建了「禁止读取其他进程内存」规则，禁止其他程序读取「C:\Windows\System32\clip.exe」，但是其他程序还是可以读取到剪贴板的内容

**Comment by wecooperate** [comment]
直接使用读取剪切板事件就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月28日(周六) 下午5:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 希望可以监控拦截剪贴板事件 (Issue #37)




  
读取剪切板是支持的，需要开启增强模式。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年12月28日(周六) 下午4:11 收件人: @.&gt;; 抄送: @.&gt;; 主题: [wecooperate/iDefender] 希望可以监控拦截剪贴板事件 (Issue #37) 希望可以监控拦截剪贴板事件。比如：读取、写入剪贴板 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
谢谢。请问监控读取剪贴板事件该怎么做？我创建了「禁止读取其他进程内存」规则，禁止其他程序读取「C:\Windows\System32\clip.exe」，但是其他程序还是可以读取到剪贴板的内容

**Comment by QPYIDRWIMG** [comment]
谢谢，找到了
